-- Baseline schema, matching the tables originally created by Hibernate's ddl-auto=update.
-- On an already-provisioned database this migration is skipped because Flyway is configured
-- with baseline-on-migrate=true and baseline-version=1 (see application.properties). It only
-- actually runs against a brand new, empty database.

CREATE TABLE IF NOT EXISTS membership_plans (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL,
    monthly_price           NUMERIC(38,2) NOT NULL,
    included_credit_hours   DOUBLE PRECISION NOT NULL,
    overage_rate_per_hour   NUMERIC(38,2) NOT NULL,
    created_at              TIMESTAMP(6) NOT NULL,
    updated_at              TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS spaces (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(255) NOT NULL CHECK (type IN ('DESK', 'MEETING_ROOM', 'PRIVATE_CABIN')),
    capacity    INTEGER NOT NULL,
    hourly_rate NUMERIC(38,2) NOT NULL,
    is_active   BOOLEAN NOT NULL,
    deleted     BOOLEAN NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    role                    VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'MEMBER')),
    api_key                 VARCHAR(255),
    membership_plan_id      BIGINT REFERENCES membership_plans(id),
    credit_hours_remaining  DOUBLE PRECISION NOT NULL,
    status                  VARCHAR(255) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    deleted                 BOOLEAN NOT NULL,
    created_at              TIMESTAMP(6) NOT NULL,
    updated_at              TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT NOT NULL,
    space_id            BIGINT NOT NULL,
    start_time          TIMESTAMP(6) NOT NULL,
    end_time            TIMESTAMP(6) NOT NULL,
    status              VARCHAR(255) NOT NULL CHECK (status IN ('CONFIRMED', 'CANCELLED', 'COMPLETED', 'WAITLISTED')),
    cost_charged        NUMERIC(38,2) NOT NULL,
    credit_hours_used   DOUBLE PRECISION NOT NULL,
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS waitlists (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    space_id        BIGINT NOT NULL,
    requested_start TIMESTAMP(6) NOT NULL,
    requested_end   TIMESTAMP(6) NOT NULL,
    status          VARCHAR(255) NOT NULL CHECK (status IN ('WAITING', 'PROMOTED', 'CANCELLED')),
    booking_id      BIGINT,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS invoices (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                         BIGINT NOT NULL,
    month                           VARCHAR(255) NOT NULL,
    total_amount                    NUMERIC(38,2) NOT NULL,
    total_credit_overage_charged    NUMERIC(38,2) NOT NULL,
    created_at                      TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS api_keys (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_hash        VARCHAR(255) NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    role            VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'MEMBER')),
    user_id         BIGINT,
    active          BOOLEAN NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    last_used_at    TIMESTAMP(6)
);
