-- Adds the reviews table backing member reviews of spaces. Reviews are always tied to a
-- COMPLETED booking (enforced in the application layer) and are soft-deleted, never hard-deleted.

CREATE TABLE IF NOT EXISTS reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    space_id    BIGINT NOT NULL,
    booking_id  BIGINT NOT NULL,
    rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     VARCHAR(500),
    deleted     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

-- Foreign keys are added defensively, matching the pattern used in
-- V2__original_cost_and_foreign_keys.sql: each one is attempted independently so unexpected
-- orphan data cannot prevent the others (or app startup) from proceeding.
DO $$
BEGIN
  BEGIN
    ALTER TABLE reviews ADD CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id);
  EXCEPTION WHEN duplicate_object THEN NULL;
  WHEN others THEN RAISE NOTICE 'Skipping fk_reviews_user: %', SQLERRM;
  END;

  BEGIN
    ALTER TABLE reviews ADD CONSTRAINT fk_reviews_space FOREIGN KEY (space_id) REFERENCES spaces(id);
  EXCEPTION WHEN duplicate_object THEN NULL;
  WHEN others THEN RAISE NOTICE 'Skipping fk_reviews_space: %', SQLERRM;
  END;

  BEGIN
    ALTER TABLE reviews ADD CONSTRAINT fk_reviews_booking FOREIGN KEY (booking_id) REFERENCES bookings(id);
  EXCEPTION WHEN duplicate_object THEN NULL;
  WHEN others THEN RAISE NOTICE 'Skipping fk_reviews_booking: %', SQLERRM;
  END;
END $$;

-- A booking may have at most one active (non-deleted) review; multiple reviews for the same
-- space are still allowed as long as they reference different bookings.
CREATE UNIQUE INDEX IF NOT EXISTS uq_reviews_booking_id_active ON reviews (booking_id) WHERE deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_reviews_space_id ON reviews (space_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews (user_id);
